### ISSUE TITLE
Problème avec Google credentials (enfin je crois) 

### ISSUE THREAD

**Issue by dextouu** [matlink/gplayweb#10]
Bonjour , j'ai fais l'installation de gplayweb ,gplaycli,fdroiserver, mais j'ai un problème, je crois avec  les ''Google credentials " de Google.
Voici le message que me sort gplaycli et gplayweb quand je lance le binaire dans mon terminal ssh .

/usr/bin/gplaycli -s canal
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 343, in <module>
    main()
  File "/usr/bin/gplaycli", line 323, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/bin/gplaycli", line 45, in connect_to_googleplay_api
    api.login(self.config["gmail_address"], self.config["gmail_password"], AUTH_TOKEN)
  File "/usr/lib/python2.7/dist-packages/ext_libs/googleplay_api/googleplay.py", line 126, in login
    response = requests.post(self.URL_LOGIN, data=params, headers=headers, verify=ssl_verify)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError

**Comment by dextouu** [comment]
Je me débrouille assez sur linux mais la je sèche.
Merci  en tous cas pour avoir dev le programme, il a l'air de bien marcher sur le serveur de démonstration.

**Comment by matlink** [comment]
Hum, je pense plutôt à une erreur SSL, de type mauvais certificat ou quelque chose dans le genre.
Quel OS utilisez-vous ?

**Comment by dextouu** [comment]
J'utilise une debian jessie sur un serveur  dédié de chez Online .

**Comment by dextouu** [comment]
J'ai installé  Gplaycli avec le deb mais le reste avec pipe, il n'y  pas de rapport ?

**Comment by dextouu** [comment]
Une question qui me vient a l'esprit, pour communiquer avec les services Google, le binaire utilise quel port ?

**Comment by matlink** [comment]
port 443, c'est du HTTPS.
Cela devrait fonctionner avec une debian jessie.
Il est possible qu'en utilisant le deb, toutes les dépendances de python ne soit pas à jour (ce qui ne devrait pas être le cas).
Je pense que ce bug est dû au fait que python ne trouve pas le CA de Google, ce qui est un problème que j'ai déjà rencontré.
Peux-tu essayer manuellement d'effectuer ce changement ? https://github.com/abeudin/gplayweb_ynh/blob/master/conf/googleplay.diff (dans le fichiers correspondant de gplaycli bien sûr)

**Comment by dextouu** [comment]
Merci Matlink, la ligne à modifier dans le fichier, a régler le problème .

**Comment by matlink** [comment]
Il faut que je fixe cela de toute manière.

**Comment by dextouu** [comment]
Bonjour ,  peut tu stp si c'est possible, me passer la conf de ton nginx pour le repo de fdroid et gplayweb .
J'ai appliqué le " proxy_pass http://127.0.0.1:8888/;" mais j'ai pense qu'il faut que je rajoute quelque chose pour qu'il me formate bien la page .

**Comment by matlink** [comment]
https://github.com/abeudin/gplayweb_ynh/blob/master/conf/nginx.conf

**Comment by dextouu** [comment]
merci

**Comment by dextouu** [comment]
Bonjour matlink, c'est bon j'ai réussi a configurer nginx, le serveur marche, mais fdroid ne marche pas.
J'ai essayé le diff sur le binaire gplayweb , après la modification du binaire, gplayweb se lance plus.
A quoi sert le crontab, c'est pour la mise à jour du répo a chaque téléchargement ?

**Comment by matlink** [comment]
peux-tu me dire pour quelle raison gplayweb ne se lance plus ? (va voir dans l'unit systemd pour savoir comment le lancer à la main)
Le crontab sert à mettre à jour les apks régulièrement (chaque jour).

**Comment by dextouu** [comment]
une erreur de copie surement, j'ai fais la même manipulation et c'est passer .

**Comment by dextouu** [comment]
La ligne de réécriture nginx: location /gplayweb/ {
        rewrite ^YNH_EXAMPLE_PATH/(.*)$ http://YNH_EXAMPLE_DOMAIN$1 redirect;
}

C'est bien comme ca qu'il faut la réécrire  ?

location /gplayweb/ {
        rewrite ^gplayweb/(.*)$ http://gpw.mondomaine.fr$1 redirect;
}

**Comment by dextouu** [comment]
J'ai aussi une information utile pour toi que je vérifie, c'est sur yunohost, j'ai une image openvz de yunohost et j'ai mis ton projet gplayweb, le serveur web me répond "forbidden.
J'ai essayé hier soir, je regarderais ce weekend, si c'est moi  ou c'est vraiment une erreur qui est utile pour ton développement .

**Comment by matlink** [comment]
pour le `YNH_EXAMPLE_DOMAIN` il faut que tu mettes `http://gpw.mondomain.fr/gplayweb`
Si tu as un forbidden, tu dois avoir des problèmes d'accès au fichier/dossier par ton serveur web. Il faut inspecter les logs.

**Comment by dextouu** [comment]
Pour Fdroid, j'ai suivi ton tutoriel sur la page Gplayweb. 
faut t'il que j'utilise aussi ton script init au lieu et place du script systemd. pour faire fonctionner fdroid?

**Comment by dextouu** [comment]
Merci pour l'info pour la règle de réécriture.

**Comment by matlink** [comment]
Non utilises celui de systemd si c'est ton système d'init. Mais regarde à la main ce qui coince lorsque GPlayWeb tente de démarrer.

**Comment by dextouu** [comment]
Bonjour Matlink, j'ai configuré l'emplacement  sdk d'android dans mon fichier .bashrc et changer l'adresse l'adresse du repo , dans le fichier config.py de frdroid.
J'ai redémarré en lançant  la commande  de mise à jour de Fdroid.
Mais Frdroid n'est pas visible dans htop, donc pas démarrer
Y a t'il une chose que j'ai manqué ou qui m'a échapper ? 
Pour la règle de rewrite, elle marche pas chez moi.
Sinon gplayweb et gplaycli fonctionne à merveille !!!

**Comment by matlink** [comment]
fdroid n'est pas un daemon, il s'exécute juste pour mettre à jour
quelques fichier .xml utile au versionning de l'application mobile.

Le 25/01/2016 18:11, kanjusei a écrit :

> Bonjour Matlink, j'ai configuré l'emplacement sdk d'android dans mon
> fichier .bashrc et changer l'adresse l'adresse du repo , dans le
> fichier config.py de frdroid.
> J'ai redémarré en lançant la commande de mise à jour de Fdroid.
> Mais Frdroid n'est pas visible dans htop, donc pas démarrer
> Y a t'il une chose que j'ai manqué ou qui m'a échapper ?
> Pour la règle de rewrite, elle marche pas chez moi.
> Sinon gplayweb et gplaycli fonctionne à merveille !!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/gplayweb/issues/10#issuecomment-174589112.

## 

Matlink - Sysadmin matlink.fr

**Comment by dextouu** [comment]
donc il y a rien à configurer ?

**Comment by dextouu** [comment]
il me marque ca : Built repo based in "/var/www/gplayweb"
with this config:
  Android SDK:                  /opt/android-sdk-linux
  Android SDK Build Tools:      /opt/android-sdk-linux/build-tools/23.0.2
  Android NDK r10e (optional):  $ANDROID_NDK
  Keystore for signing key:     keystore.jks

**Comment by matlink** [comment]
simplement l'installation de fdroid etc ... bien vérifier que gplayweb
appelle fdroid quand il a téléchargé une appli, ...

Le 25/01/2016 18:15, kanjusei a écrit :

> donc il y a rien à configurer ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/gplayweb/issues/10#issuecomment-174590274.

## 

Matlink - Sysadmin matlink.fr

**Comment by dextouu** [comment]
et comment tu le vérifie?

Je vois le même dossier que sur ton repo mais quand je le rajoute a l'application, elle me dis erreur: impossible de récupérer l'index.

**Comment by dextouu** [comment]
![2016-01-25_18-27-42](https://cloud.githubusercontent.com/assets/16746195/12558759/a3ffc028-c391-11e5-8770-83add8a8ecfc.png)

**Comment by dextouu** [comment]
une question, tu n'a pas touché au fichier config.py quand tu as créer ton repo de démonstration ?

**Comment by matlink** [comment]
Peux-tu créer une nouvelle issue puisqu'on a changé de sujet ? à partir de https://github.com/matlink/gplayweb/issues/10#issuecomment-173659646 stp, car ensuite je vais les supprimer.
