### ISSUE TITLE
CSS not charging

### ISSUE THREAD

**Issue by Julian2412** [matlink/gplayweb#15]
Hi, 

I have installed GPlayWeb from pip on Debian Jessie everythings works fine exepted that CSS is not charging. I have no style on the GPlayWeb UI. 

![screeshot_gplayweb](https://cloud.githubusercontent.com/assets/8627555/15359161/5faf80a4-1d08-11e6-8f11-9728e6bb9792.PNG)

I have verified rights, and all what I can.

Matlink, I send you mails some month ago in french for the same issue on an other server.

Thanks for this uselfull soft =)

Have a good day !

Julian

**Comment by matlink** [comment]
Can you check the source code of this page, and give me the URL of the css file ? I think there is an extra '/' at the beginning of the url.

**Comment by Julian2412** [comment]
rel="stylesheet" href="//static/css/bootstrap.min.css?v=5d5357cb3704e1f43a1f5bfed2aebf42"

Is that link ?

edit : I removed link balise

**Comment by matlink** [comment]
Yes, that link, there is an extra '/' at the beginning. I'm aware of that bug, the github version is patched, but not the pip one. Let me publish the patched version to pip (doing it now).

**Comment by matlink** [comment]
You can upgrade gplayweb in order to test if the patch works. Restart your webserver to avoir any cache issue.

**Comment by Julian2412** [comment]
Wonderful !! Thanks for all it's really better =)

I love your work !

Julian
