### ISSUE TITLE
yunohost app

### ISSUE THREAD

**Issue by beudbeud** [matlink/gplayweb#2]
hello can you make a yunohost app for gplayweb

thanks

**Comment by matlink** [comment]
working on it, without fdroidserver compatibility for now. I think I'm gonna add a fdroidserver_ynh app, that could be interesting.

**Comment by beudbeud** [comment]
good to know :)

**Comment by matlink** [comment]
Should be ready for tests : https://github.com/matlink/gplayweb_ynh
Not in a virtualenv, I can't get it work with it, seems hard to deploy from a bash script.
