### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by beudbeud** [matlink/gplayweb#3]
i have this message 

debian wheezy

```
sudo pip install -r gplaycli/requirements.txt
Downloading/unpacking requests>=0.12 from https://pypi.python.org/packages/source/r/requests/requests-2.7.0.tar.gz#md5=29b173fd5fa572ec0764d1fd7b527260 (from -r gplaycli/requirements.txt (line 1))
  Downloading requests-2.7.0.tar.gz (451Kb): 451Kb downloaded
  Running setup.py egg_info for package requests

Downloading/unpacking protobuf>=2.4 (from -r gplaycli/requirements.txt (line 2))
  Running setup.py egg_info for package protobuf
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/beudbeud/gplayweb/build/protobuf/setup.py", line 212, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 263, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 288, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 863, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 492, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (six 1.1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/beudbeud/gplayweb/build/protobuf/setup.py", line 212, in <module>

    "Protocol Buffers are Google's data interchange format.",

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 263, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 288, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 618, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 863, in best_match

    dist = working_set.find(req)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 492, in find

    raise VersionConflict(dist, req)

pkg_resources.VersionConflict: (six 1.1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5'))
```

**Comment by matlink** [comment]
Distro ?

Le 29/08/2015 12:04, abeudin a écrit :

> i have this message
> 
> |sudo pip install -r gplaycli/requirements.txt Downloading/unpacking
> requests>=0.12 from
> https://pypi.python.org/packages/source/r/requests/requests-2.7.0.tar.gz#md5=29b173fd5fa572ec0764d1fd7b527260
> (from -r gplaycli/requirements.txt (line 1)) Downloading
> requests-2.7.0.tar.gz (451Kb): 451Kb downloaded Running setup.py
> egg_info for package requests Downloading/unpacking protobuf>=2.4
> (from -r gplaycli/requirements.txt (line 2)) Running setup.py egg_info
> for package protobuf Traceback (most recent call last): File
> "<string>", line 14, in <module> File
> "/home/beudbeud/gplayweb/build/protobuf/setup.py", line 212, in
> <module> "Protocol Buffers are Google's data interchange format.",
> File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
> _setup_distribution = dist = klass(attrs) File
> "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 263,
> in __init__ self.fetch_build_eggs(attrs['setup_requires']) File
> "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 288,
> in fetch_build_eggs replace_conflicting=True, File
> "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 618,
> in resolve dist = best[req.key] = env.best_match(req, ws, installer)
> File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line
> 863, in best_match dist = working_set.find(req) File
> "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 492,
> in find raise VersionConflict(dist, req)
> pkg_resources.VersionConflict: (six 1.1.0
> (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5'))
> Complete output from command python setup.py egg_info: Traceback (most
> recent call last): File "<string>", line 14, in <module> File
> "/home/beudbeud/gplayweb/build/protobuf/setup.py", line 212, in
> <module> "Protocol Buffers are Google's data interchange format.",
> File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
> _setup_distribution = dist = klass(attrs) File
> "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 263,
> in __init__ self.fetch_build_eggs(attrs['setup_requires']) File
> "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 288,
> in fetch_build_eggs replace_conflicting=True, File
> "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 618,
> in resolve dist = best[req.key] = env.best_match(req, ws, installer)
> File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line
> 863, in best_match dist = working_set.find(req) File
> "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 492,
> in find raise VersionConflict(dist, req)
> pkg_resources.VersionConflict: (six 1.1.0
> (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5')) |
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/gplayweb/issues/3.

## 

Matlink - Sysadmin matlink.fr

**Comment by beudbeud** [comment]
c'est une debian wheezy i386

**Comment by matlink** [comment]
Tu peux essayer d'installer gplaycli `pip install gplaycli` à la place ?

Le 29/08/2015 12:12, abeudin a écrit :

> c'est une debian wheezy i386
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/gplayweb/issues/3#issuecomment-135968401.

## 

Matlink - Sysadmin matlink.fr

**Comment by matlink** [comment]
Ou bien un `pip install six --upgrade`

**Comment by beudbeud** [comment]
merci c'est good avec le upgrade
