### ISSUE TITLE
Problem locating gplaycli.gplaycli

### ISSUE THREAD

**Issue by 0uro** [matlink/gplayweb#4]
Hello,

Freshly cloned and installed gplaycli and gplayweb (with python setup.py install), and I get that :+1: 

~# gplayweb
Traceback (most recent call last):
  File "/usr/local/bin/gplayweb", line 4, in <module>
    **import**('pkg_resources').run_script('GPlayWeb==0.1', 'gplayweb')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/GPlayWeb-0.1-py2.7.egg/EGG-INFO/scripts/gplayweb", line 6, in <module>

ImportError: No module named gplaycli.gplaycli

**Comment by matlink** [comment]
Gonna have a look at it, busy right now, in a hour or two.

Le 02/09/2015 12:50, 0uro a écrit :

> Hello,
> 
> Freshly cloned and installed gplaycli and gplayweb (with python
> setup.py install), and I get that :+1:
> 
> ~# gplayweb
> Traceback (most recent call last):
> File "/usr/local/bin/gplayweb", line 4, in
> _import_('pkg_resources').run_script('GPlayWeb==0.1', 'gplayweb')
> File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in
> run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445,
> in run_script
> exec(script_code, namespace, namespace)
> File
> "/usr/local/lib/python2.7/dist-packages/GPlayWeb-0.1-py2.7.egg/EGG-INFO/scripts/gplayweb",
> line 6, in
> 
> ImportError: No module named gplaycli.gplaycli
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/gplayweb/issues/4.

## 

Matlink - Sysadmin matlink.fr

**Comment by matlink** [comment]
Fixed by https://github.com/matlink/gplaycli/commit/f6fda63a8077ba2f101cf69ca58a5a7767784e10
Could you update your gplaycli git repo and reinstall ? 
`cd gplaycli && git pull && python setup.py install`

**Comment by 0uro** [comment]
That fixed it, good job :)
