### ISSUE TITLE
ubuntu14.04: gplayweb doesn't start on boot

### ISSUE THREAD

**Issue by evrardjp** [matlink/gplayweb#5]
Even if you add the init.d/gplayweb with update-rc.d gplayweb defaults/enable, the script doesn't seem to work.

I've edited the gplayweb init.d script, replacing this:
  # Required-Start: $network nginx $syslog

no luck.

**Comment by matlink** [comment]
Is it just not starting ?
What's in your /etc/rc*.d/ folder ? Is S??gplayweb present ?

**Comment by evrardjp** [comment]
It is.

It just fails.

Manually starting after boot with /etc/init.d/gplayweb start works.

I can drop you the files included in the /etc/rc*.d folder if you want.

**Comment by matlink** [comment]
I just need to now if S??gplayweb is in these fodlers

**Comment by evrardjp** [comment]
it is.
root@gplaystore:/etc# ls -lR | grep gpl
(...)
lrwxrwxrwx 1 root root  18 Sep  6 14:57 K20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 K20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 S20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 S20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 S20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 S20gplayweb -> ../init.d/gplayweb
lrwxrwxrwx 1 root root  18 Sep  6 14:57 K20gplayweb -> ../init.d/gplayweb

**Comment by matlink** [comment]
I'll need to remove nginx dependency to start. It definitely should work like it. I'm checking what's wrong by my side.

**Comment by evrardjp** [comment]
I have installed nginx to serve the static files and the fdroid repo, so it's not really an issue for me.

If I add a sleep 30 before the start-stop-daemon, I see the script init running, but at the end, the process isn't started. 

I guess it's really something with the start-stop-daemon line.

**Comment by matlink** [comment]
$DAEMON seems empty. `which gplayweb` returns nothing during init.

**Comment by evrardjp** [comment]
Ok I'll fill the variable with the correct path.
Do you plan to do the same, or use a workaround/another process monitor (like supervisord)?

**Comment by matlink** [comment]
Yep, I'll make a patch

**Comment by evrardjp** [comment]
thanks

**Comment by matlink** [comment]
Fixed by 86db5a69d9dc67b0607503985dbad49c338cfb8
