### ISSUE TITLE
Service fail to start on Debian jessie

### ISSUE THREAD

**Issue by plopoyop** [matlink/gplayweb#9]
Hi, 
On debian jessie ( and I think on every systems based on systemd), gplayweb fail to start with message : 
Failed to start gplayweb.service: Unit gplayweb.service failed to load: No such file or directory.

I created a working file that work :
[Unit]
Description=GplayWeb
After=network.target

[Service]
ExecStart=/usr/local/bin/gplayweb
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

I don't know how to make the corresponding pull request.
The file should be created as : /lib/systemd/system/gplayweb.service

**Comment by matlink** [comment]
Yes, I didn't write a systemd unit. I added it via 7bc25e00d34b3dd5782d227aa09d366a1a87a603. Thank you.
Btw, couldn't you put this file in another location ? I think in `/etc` there is something for that. For custom services.
